flowchart TD
    node1{"Is it Health Care data?"}
    node2{"Is it healthy Volunteer data ?"}
    node3{"I know the specific data I want"}
    node4{"Is registration required?"}
    node5{"Prospective/Retrospective Data"}
    node6{"Observational /interventional/ Research Ratabase"}
    node7{"Anonymised/ Pseudo/ contains indentifiers"}
    node8{"Public or Private Dataset"}
    node9["Conclusion"]
    node10["Conclusion"]
    node11["1st port of call LRECmoodle page - update to ad..."]
    node12["include tool tips with definition of terms"]
    node13["&lt;1000 case only what is option if &gt;1000 ?"]
    node14["Conclusion"]
    node15["Conclusion"]
    node16["Conclusion"]
    node17["Conclusion"]
    node18["Conclusion"]
    node19["Conclusion"]
    node20["Conclusion"]
    node21["Public datasets/ repositoriesOMOP Cat"]

    node1 -->|"YES"| node3
    node1 -->|"NO"| node2
    node2 -->|"YES"| node20
    node2 -->|"I don't know"| node17
    node3 -->|"NO"| node18
    node3 -->|"YES"| node8
    node4 -->|"YES"| node19
    node4 -->|"NO"| node10
    node5 -->|"Retrospective"| node7
    node5 -->|"Prospective"| node6
    node6 -->|"Observational /Interventional/Research Database"| node16
    node7 -->|"Pseudonymised or Anonymised"| node14
    node7 -->|"Indentifiers"| node15
    node8 -->|"Public"| node4
    node8 -->|"Private"| node5
    node9 --> node1